name: IPQ60XX-LibWrt

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 20 * * *'

jobs:
  Build:
    uses: ./.github/workflows/reusable-openwrt-build.yml
    secrets: inherit
    with:
      repo_url: https://github.com/laipeng668/openwrt-6.x.git
      repo_branch: main-nss
      config_file: configs/IPQ60XX.config
      general_config_file: configs/General.config
      diy_script: scripts/Roc-script.sh
      firmware_tag: IPQ60XX
      firmware_release: true
      upload_bin_dir: false
      tz: Asia/Shanghai
      target_profile: ipq60xx
      cleanup_workflow_runs: false
