name: JDCloud-ImmortalWrt

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 20 * * *'

jobs:
  Build:
    uses: ./.github/workflows/reusable-openwrt-build.yml
    secrets: inherit
    with:
      repo_url: https://github.com/laipeng668/immortalwrt.git
      repo_branch: openwrt-25.12
      config_file: configs/JDCloud.config
      general_config_file: configs/General.config
      diy_script: scripts/Roc-script.sh
      firmware_tag: JDCloud
      firmware_release: true
      upload_bin_dir: false
      tz: Asia/Shanghai
      target_profile: jdcloud
      cleanup_workflow_runs: true
